name: absensi_cifo_v2
description: "Absensi CIFO Update."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_background_service: ^5.1.0
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  socket_io_client: ^3.0.2
  logger: ^2.5.0
  workmanager: ^0.5.2
  rename_app: ^1.6.1
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.5
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  cherry_toast: ^1.11.0
  dropdown_textfield: ^1.2.0
  shimmer: ^3.0.0
  panara_dialogs: ^0.1.5
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  intl: ^0.20.1
  timezone: ^0.10.0
  location: ^7.0.1
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  flutter_screenutil: ^5.9.3
  battery_plus: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding images from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
